# NumPy: Package for Multidimentional array

## Vector(1d)
## Matrix (2d or 1d)

## Create an array

In [ ]:
# pip install numpy --- if numpy is not working

In [2]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [4]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(5,28) # 5-27 number, create number between 5-27 step size 1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [12]:
np.arange(5,35,6) # 5-34 number, create number between 5-27 step size 6

array([ 5, 11, 17, 23, 29])

In [13]:
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.zeros(6, dtype = int)

array([0, 0, 0, 0, 0, 0])

In [15]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [17]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [18]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [19]:
np.ones((2,5), dtype = int)  # create array of 2*5 with all 1 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.linspace(0,1) # create 50 equal parts between 0 and 1 

array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

In [25]:
np.linspace(0,20,10) # create 10 equal parts between 0 and 20 

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [24]:
np.linspace(0,20,10, dtype = int) # create 10 equal parts between 0 and 20 

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [26]:
np.linspace(0,10,15)  # create 15 equal parts between 0 and 10 

array([  0.        ,   0.71428571,   1.42857143,   2.14285714,
         2.85714286,   3.57142857,   4.28571429,   5.        ,
         5.71428571,   6.42857143,   7.14285714,   7.85714286,
         8.57142857,   9.28571429,  10.        ])

In [27]:
np.eye(5, dtype=int)   # Identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
np.random.rand(2,4)  ### uniform distribution between 0 and 1 -- 2*4

array([[ 0.11757909,  0.28998756,  0.26158782,  0.30700973],
       [ 0.98670773,  0.97926719,  0.48348281,  0.88796156]])

In [29]:
np.random.randn(2,4) ### standard normal distribution -- 2*4, it will include positive & negative value

array([[ 0.28791891, -1.51066213,  1.08842494,  0.96775523],
       [ 0.22156769,  0.01798672,  0.12823311, -0.3919142 ]])

In [30]:
np.random.rand(2,5)

array([[ 0.90885853,  0.47937871,  0.74037243,  0.10415349,  0.19459399],
       [ 0.17993375,  0.95624282,  0.21373478,  0.69541417,  0.02443001]])

In [31]:
np.random.randint(0,10,100) # create 100 random int value between 0-9

array([6, 0, 8, 2, 3, 1, 7, 1, 4, 3, 1, 8, 0, 8, 6, 5, 8, 8, 7, 2, 4, 1, 2,
       7, 8, 2, 4, 9, 6, 4, 3, 5, 1, 8, 0, 6, 2, 3, 6, 7, 2, 6, 2, 4, 0, 4,
       7, 3, 1, 9, 0, 3, 7, 8, 1, 9, 9, 8, 3, 9, 5, 8, 7, 1, 9, 0, 6, 1, 1,
       4, 4, 7, 0, 5, 4, 1, 3, 7, 4, 6, 7, 1, 9, 0, 8, 5, 2, 9, 3, 8, 0, 3,
       1, 7, 3, 5, 1, 8, 3, 3])

In [34]:
np.random.randint(10,100,15) # create 15 random int value between 10-99

array([26, 89, 98, 28, 70, 45, 37, 96, 90, 80, 29, 11, 26, 80, 23])

In [35]:
np.random.randint(20,56,100) # create 100 random int value between 20-55

array([29, 22, 37, 51, 45, 27, 22, 37, 50, 25, 43, 50, 36, 22, 27, 22, 54,
       20, 31, 42, 25, 37, 49, 43, 50, 50, 42, 25, 42, 21, 24, 38, 32, 23,
       47, 38, 34, 48, 21, 43, 27, 25, 33, 45, 22, 31, 42, 30, 32, 43, 33,
       46, 34, 23, 24, 20, 46, 31, 41, 36, 43, 34, 50, 29, 49, 52, 20, 37,
       27, 55, 20, 25, 43, 51, 41, 26, 43, 27, 34, 55, 46, 46, 23, 50, 52,
       30, 22, 33, 27, 43, 20, 26, 49, 33, 27, 21, 29, 36, 22, 39])

In [36]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [37]:
rand_array=np.random.randint(0,10,5)
rand_array

array([3, 2, 9, 2, 8])

In [38]:
sample_array.min()

2

In [39]:
sample_array.argmin()  ## index of min position

0

In [40]:
sample_array.argmax() ## index of max position

17

In [41]:
rand_array.argmin()

1

In [42]:
rand_array.argmax()

2

In [43]:
rand_array.max()

9

In [44]:
rand_array.min()

2

In [45]:
sample_array.dtype

dtype('int32')

In [46]:
rand_array.dtype

dtype('int32')

In [47]:
a=np.eye(5)
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [48]:
a=np.eye(5, dtype = int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [52]:
a=np.random.rand(2,2)
a

array([[ 0.76794985,  0.52515659],
       [ 0.21726948,  0.66975709]])

In [50]:
a=np.random.rand(2,3)
a

array([[ 0.32505211,  0.48192594,  0.57417445],
       [ 0.04303294,  0.96814732,  0.41107206]])

In [53]:
a.T  #transpose row to columm


array([[ 0.76794985,  0.21726948],
       [ 0.52515659,  0.66975709]])

In [54]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [55]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [56]:
sample_array=sample_array.reshape(3,4)  ## error because new array size = 12 and existing = 18
sample_array

ValueError: total size of new array must be unchanged

In [57]:
sample_array[5] = 100  ## 5th row , all value 100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [58]:
sample_array = np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [59]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [61]:
sample_array[3:9] ## 13, 14, 15, 16, 17, 18

array([13, 14, 15, 16, 17, 18])

In [62]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [64]:
sample_array[:] = 1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

# 2D - Array

In [3]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [4]:
sample_matrix[2][2]

24

In [5]:
sample_matrix[2,2]

24

In [6]:
sample_matrix[1][2]

54

In [7]:
sample_matrix[1,2]

54

In [68]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [8]:
sample_matrix[1,1]

2

In [70]:
sample_matrix[1:3, 2:4]

array([[54, 65],
       [24,  7]])

In [71]:
sample_matrix[1:, 2:]

array([[54, 65],
       [24,  7]])

In [72]:
sample_matrix[2]

array([56, 76, 24,  7])

In [ ]:
sample_array=np.arange(1,31)
sample_array

## Assignment - with Krishan

In [73]:
#Write a Program to check the version numpy installed .

print(np.__version__)

1.11.1


In [74]:
#Write a program to create numpy 1-D array from list.

simple_list=[6,7,8]
a = np.array(simple_list)
a

array([6, 7, 8])

In [75]:
#Write a program to Create a 2-D array 

sample_array=np.array(([1,2,3],[4,5,6],[7,8,9,]))
sample_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
array_2d = np.random.rand(2,2)
array_2d

array([[ 0.73140843,  0.77119723],
       [ 0.78731915,  0.29053754]])

In [9]:
# What is the output [5 9]
# a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])

a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [10]:
a[1:, 2:3]   ## [5 9]

array([[5],
       [9]])

In [11]:
a[1:, 2]

array([5, 9])

In [86]:
## 4 5
## 8 9
a[1:, 1:3]

array([[4, 5],
       [8, 9]])

In [79]:
a[0:3:2, 0:3:2]   # skipping 2nd row

array([[1, 3],
       [7, 9]])

In [12]:
a[-1:5] 

array([[ 7,  8,  9, 10]])

In [ ]:
a=np.array([(1,5,9),(10,12,2),(5,7,8)])

In [ ]:
print(a[0].max())
print(a[0].min())
print(a[0].sum())

In [ ]:
# Create a [3,4] numpy array and reshape it [4,3] numpy array.

a=np.arange(1,13)
b=a.reshape(3,4)
c=b.reshape(4,3)
print(b)
print(c)

In [ ]:
a=np.arange(1,13)
b=a.reshape(3,4)
b

In [ ]:
array1 = np.random.randint(100, size=(2,10))
array2 = np.random.randint(100, size=(2,10))
print(array1)
print(array2)

np.vstack((array1,array2))   # concatenate - virtically
np.hstack((array1,array2))   # concatenate - horizontally

In [ ]:
print(array1)
np.where(array1==93)

In [ ]:
array1 = np.random.randint(100, size=(3,3))
array1

In [ ]:
np.delete(array1,1,axis=1) #asis=1 means 

In [ ]:
array1[:,1] = np.array([[10,10,10]])
array1

In [ ]:
#Practice -1 
a=np.array([(31,29,44),(62,19,65)])
a

In [ ]:
a[0:1,1:2]

In [ ]:
# practice - 2
a=np.array([(2,6,8),(1,5,4),(4,3,2)])
a,a[:,1], a[1,1:]

#----------------------------------------------------#

# NumPy - 2nd Class

In [2]:
import numpy as np

In [3]:
sample_array = np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [4]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [5]:
np.exp(sample_array)

array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03,
         2.20264658e+04,   5.98741417e+04,   1.62754791e+05,
         4.42413392e+05,   1.20260428e+06,   3.26901737e+06,
         8.88611052e+06,   2.41549528e+07,   6.56599691e+07,
         1.78482301e+08,   4.85165195e+08,   1.31881573e+09,
         3.58491285e+09,   9.74480345e+09,   2.64891221e+10,
         7.20048993e+10,   1.95729609e+11,   5.32048241e+11,
         1.44625706e+12,   3.93133430e+12,   1.06864746e+13])

In [6]:
np.sqrt(sample_array)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766,
        3.31662479,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558])

In [7]:
np.log(sample_array)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436,  1.60943791,
        1.79175947,  1.94591015,  2.07944154,  2.19722458,  2.30258509,
        2.39789527,  2.48490665,  2.56494936,  2.63905733,  2.7080502 ,
        2.77258872,  2.83321334,  2.89037176,  2.94443898,  2.99573227,
        3.04452244,  3.09104245,  3.13549422,  3.17805383,  3.21887582,
        3.25809654,  3.29583687,  3.33220451,  3.36729583,  3.40119738])

In [8]:
np.max(sample_array)

30

In [9]:
np.min(sample_array)

1

In [10]:
np.argmax(sample_array)  ## index of max value

29

In [11]:
np.argmin(sample_array)  ## index of min value

0

In [12]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [13]:
np.std(sample_array)  ## Standard deviation 

8.6554414483991895

In [14]:
np.var(sample_array)  ## Variance 

74.916666666666671

In [15]:
np.mean(sample_array)  ## mean

15.5

In [16]:
array = np.random.randn(3,4)  ## standard normal distribution
array

array([[ 1.04354576, -0.18844556,  0.849681  ,  0.65483266],
       [-0.99442796, -0.38448719,  1.59513329, -1.54919753],
       [-1.98136646, -0.56977025, -0.72627139, -0.37270006]])

In [17]:
np.round(array,decimals=3)

array([[ 1.044, -0.188,  0.85 ,  0.655],
       [-0.994, -0.384,  1.595, -1.549],
       [-1.981, -0.57 , -0.726, -0.373]])

In [18]:
sport = np.array(['golf','cricket','fball','cricket','basletball'])
np.unique(sport)

array(['basletball', 'cricket', 'fball', 'golf'], 
      dtype='<U10')

In [ ]:
##------------------------------------------------------------##