In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [2]:
import numpy as np 
array=np.array([1,2,3,4,5,6])
print(array[0:3:2])


[1 3]


In [ ]:
import numpy as np 
array=np.array([1,2,3,4,5,6])
print(array[-3:-1])

[4 5]


In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 3))

print(x)

[[7 7 3]
 [9 3 7]
 [3 3 7]]


In [4]:
import numpy as np 

a=np.array([1,2,3])
b=np.array([2,3,4])

c=a+b

print(c)


[3 5 7]


In [7]:
c

array([3, 5, 7])

In [ ]:
import numpy as np 

a=np.array([1,2,3])
b=np.array([2,3,4])

print(np.dot(a,b))

20


In [ ]:
a=np.array([[1,2,3],[2,2,3]])
b=np.array([[2,5],[5,4],[7,8]])
print(np.dot(a,b))

[[33 37]
 [35 42]]


In [ ]:
a=np.array([[1,2,3],[2,2,3]])
b=np.array([[2,5,6],[5,4,7]])
print(a-b)

[[-1 -3 -3]
 [-3 -2 -4]]


In [ ]:
import numpy as np 
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
import numpy as np
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])